CREATE DATABASE MovimentosManuais
GO

USE MovimentosManuais
GO

EXEC sp_changedbowner 'sa'
GO

CREATE TABLE PRODUTO (
	COD_PRODUTO CHAR(4) PRIMARY KEY
	,DES_PRODUTO VARCHAR(30) 
	,STA_STATUS CHAR(1)

	,CONSTRAINT CHK_STA_STATUS_PRODUTO CHECK (STA_STATUS = 'A' OR STA_STATUS = 'I' OR STA_STATUS = NULL)
)
GO

CREATE TABLE PRODUTO_COSIF(
	COD_PRODUTO CHAR(4) NOT NULL
	,COD_COSIF VARCHAR(11) NOT NULL
	,COD_CLASSIFICACAO CHAR(6)
	,STA_STATUS CHAR(1)

	PRIMARY KEY (COD_PRODUTO, COD_COSIF)
	,CONSTRAINT FK_PRODUTO_COSIF_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
	,CONSTRAINT CHK_STA_STATUS_PRODUTO_COSIF CHECK (STA_STATUS = 'A' OR STA_STATUS = 'I' OR STA_STATUS = NULL)
)
GO

CREATE TABLE MOVIMENTO_ANUAL(
	DTA_MES INT NOT NULL
	,DTA_ANO INT NOT NULL
	,NUM_LANCAMENTO INT NOT NULL
	,COD_PRODUTO CHAR(4) NOT NULL
	,COD_COSIF VARCHAR(11) NOT NULL
	,VAL_VALOR DECIMAL (18,2) NOT NULL
	,DES_DESCRICAO VARCHAR(50) NOT NULL
	,DAT_MOVIMENTO SMALLDATETIME NOT NULL
	,COD_USUARIO VARCHAR(15) NOT NULL

	PRIMARY KEY (DTA_MES,DTA_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF)
	,CONSTRAINT FK_MOVIMENTO_ANUAL_PRODUTO_COSIF FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF (COD_PRODUTO, COD_COSIF)
)
GO

INSERT INTO PRODUTO 
VALUES 
	('1', 'Produto Teste', 'A')
	,('2', 'Produto Teste2', 'A')
GO

INSERT INTO PRODUTO_COSIF
VALUES 
	('1', '1', '1', 'A')
	,('1', '2', '1', 'A')
	,('1', '3', '1', 'A')
	,('2', '1', '1', 'A')
GO

INSERT INTO MOVIMENTO_ANUAL
VALUES
	(2, 2012, 1, '1', '1', 500, 'Teste Movimentos', '2012-02-01', '1')
	,(2, 2012, 2, '2', '1', 10, 'Teste Movimentos 2', '2012-02-01', '1')
	,(2, 2012, 3, '1', '2', 12, 'Teste Movimentos 2', '2012-02-01', '1')
	,(2, 2012, 4, '1', '3', 100, 'Teste Movimentos 4', '2012-02-01', '1')
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('ManualMovimentationList'))
   DROP PROCEDURE ManualMovimentationList
GO

CREATE PROC ManualMovimentationList (
	@Month INT = NULL
) AS
BEGIN
	SELECT
		MM.DAT_MES				[Month]
		,MM.DAT_ANO				[Year]
		,MM.COD_PRODUTO			[ProductCod]
		,MM.COD_COSIF			[CosifCod]
		,P.DES_PRODUTO			[ProductDescription]
		,MM.NUM_LANCAMENTO		[ReleaseNumber]
		,MM.DES_DESCRICAO		[ReleaseDescription]
		,MM.VAL_VALOR			[Value]
	FROM MOVIMENTO_ANUAL AS MM
	INNER JOIN PRODUTO_COSIF AS PC ON MM.COD_PRODUTO = PC.COD_PRODUTO AND MM.COD_COSIF = PC.COD_COSIF
	INNER JOIN PRODUTO AS P ON P.COD_PRODUTO = PC.COD_PRODUTO
	ORDER BY
		MM.DAT_MES
		,MM.DAT_ANO
		,MM.NUM_LANCAMENTO
END
GO

EXEC ManualMovimentationList
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('ManualMovimentationInsert'))
   DROP PROCEDURE ManualMovimentationInsert
GO

CREATE PROC ManualMovimentationInsert (
	@Month INT
	,@Year INT 
	,@ProductCod CHAR(4)
	,@CosifCod VARCHAR(11)
	,@Value DECIMAL(18,2)
	,@DesDescription VARCHAR(50)
	,@MovementDate SMALLDATETIME
	,@UserCod VARCHAR(15)
) AS
BEGIN
	DECLARE @ReleaseNumber INT = (SELECT 
									COUNT(*) 
								FROM MOVIMENTO_ANUAL
								) + 1

	INSERT INTO MOVIMENTO_ANUAL (
		DAT_MES
		,DAT_ANO
		,NUM_LANCAMENTO
		,COD_PRODUTO
		,COD_COSIF
		,VAL_VALOR
		,DES_DESCRICAO
		,DAT_MOVIMENTO
		,COD_USUARIO
	)
	VALUES (
		@Month
		,@Year
		,@ReleaseNumber
		,@ProductCod
		,@CosifCod
		,@Value
		,@DesDescription
		,@MovementDate
		,@UserCod
	)
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('FieldsList'))
   DROP PROCEDURE FieldsList
GO

CREATE PROC FieldsList (
	@UserCod VARCHAR(15) = NULL
) AS
BEGIN
	SELECT
		COD_PRODUTO		[ProductCod]
		,DES_PRODUTO	[ProductDescription]
	FROM PRODUTO

	SELECT 
		COD_PRODUTO		[ProductCod]
		,COD_COSIF		[CosifCod]
	FROM PRODUTO_COSIF
END
GO

EXEC FieldsList