CREATE DATABASE antliaTeste
GO

USE antliaTeste
GO

EXEC sp_changedbowner 'sa'
GO

CREATE TABLE PRODUTO (
	COD_PRODUTO CHAR(4) PRIMARY KEY
	,DES_PRODUTO VARCHAR(30) 
	,STA_STATUS CHAR(1)

	,CONSTRAINT CHK_STA_STATUS_PRODUTO CHECK (STA_STATUS = 'A' OR STA_STATUS = 'I' OR STA_STATUS = NULL)
)
GO

CREATE TABLE PRODUTO_COSIF(
	COD_PRODUTO CHAR(4) NOT NULL
	,COD_COSIF VARCHAR(11) NOT NULL
	,COD_CLASSIFICACAO CHAR(6)
	,STA_STATUS CHAR(1)

	PRIMARY KEY (COD_PRODUTO, COD_COSIF)
	,CONSTRAINT FK_PRODUTO_COSIF_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
	,CONSTRAINT CHK_STA_STATUS_PRODUTO_COSIF CHECK (STA_STATUS = 'A' OR STA_STATUS = 'I' OR STA_STATUS = NULL)
)
GO

CREATE TABLE MOVIMENTO_MANUAL(
	DTA_MES INT NOT NULL
	,DTA_ANO INT NOT NULL
	,NUM_LANCAMENTO INT NOT NULL
	,COD_PRODUTO CHAR(4) NOT NULL
	,COD_COSIF VARCHAR(11) NOT NULL
	,VAL_VALOR DECIMAL (18,2) NOT NULL
	,DES_DESCRICAO VARCHAR(50) NOT NULL
	,DAT_MOVIMENTO SMALLDATETIME NOT NULL
	,COD_USUARIO VARCHAR(15) NOT NULL

	PRIMARY KEY (DTA_MES,DTA_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF)
	,CONSTRAINT FK_MOVIMENTO_MANUAL_PRODUTO_COSIF FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF (COD_PRODUTO, COD_COSIF)
)
GO

INSERT INTO PRODUTO 
VALUES 
	('1', 'Produto Teste', 'A')
	,('2', 'Produto Teste2', 'A')
GO

INSERT INTO PRODUTO_COSIF
VALUES 
	('1', '1', '1', 'A')
	,('1', '2', '1', 'A')
	,('1', '3', '1', 'A')
	,('2', '1', '1', 'A')
GO

INSERT INTO MOVIMENTO_MANUAL
VALUES
	(2, 2012, 1, '1', '1', 500, 'Teste Movimentos', '2012-02-01', '1')
	,(2, 2012, 2, '2', '1', 10, 'Teste Movimentos 2', '2012-02-01', '1')
	,(2, 2012, 3, '1', '2', 12, 'Teste Movimentos 2', '2012-02-01', '1')
	,(2, 2012, 4, '1', '3', 100, 'Teste Movimentos 4', '2012-02-01', '1')
GO